In [63]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import collections
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Load the training data into feature matrix, class labels, and event ids:

In [64]:
from proj1_helpers import *
DATA_TRAIN_PATH = '../data/train.csv'
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [65]:
from implementations import *

## Do your thing crazy machine learning thing here :) ...

### Testing functions

In [66]:
#GD
initial_w=np.zeros(tX.shape[1])
max_iters=50
gamma=1e-1
w,loss = least_squares_GD(y,tX,initial_w,max_iters,gamma)
print(f'w:{w}\nloss:{loss}')

w:[-4.54923076e+282  2.28877997e+282  3.44914262e+282  1.32768179e+282
 -4.28465514e+283 -4.35313371e+283 -4.28400596e+283  1.07251294e+281
  6.14903484e+281  4.19957674e+282  5.93063550e+280 -2.10909762e+280
 -4.28437769e+283  1.49000734e+282 -6.83515162e+278 -5.32642641e+278
  1.84170287e+282 -1.27975893e+279  1.82888164e+279  1.43856554e+282
 -7.48343795e+278  6.33994079e+282  1.42853297e+280 -2.56196364e+283
 -2.65631526e+283 -2.65633841e+283 -4.29028832e+283 -4.28431938e+283
 -4.28432022e+283  8.67866511e+281]
loss:inf


In [67]:
#SDG
initial_w=np.zeros(tX.shape[1])
max_iters=20
gamma=1e-4
w,loss = least_squares_SGD(y,tX,initial_w,max_iters,gamma)
print(f'w:{w}\nloss:{loss}')

w:[ 1.46183656e+44  1.24827887e+44  1.21848164e+44  3.71262738e+43
 -1.56920987e+45 -1.56922425e+45 -1.56920975e+45  3.60176358e+42
  3.71285549e+43  1.19833860e+44  2.21430460e+42 -1.80012948e+42
 -1.56920983e+45  4.97367079e+43  1.07920608e+42  5.58293804e+41
  7.00982694e+43  2.86723266e+42 -2.57934380e+42  5.59033257e+43
  2.61107881e+42  2.64514583e+44 -3.11584980e+37 -1.56921109e+45
 -1.56920978e+45 -1.56920982e+45 -1.56921081e+45 -1.56920985e+45
 -1.56920983e+45 -2.68855344e+39]
loss:1.2361401739286464e+92


In [68]:
#LS
w,loss = least_squares(y,tX)
print(f'w:{w}\nloss:{loss}')

w:[ 8.03494312e-05 -7.20202273e-03 -6.05417273e-03 -5.47559065e-04
 -1.93874700e-02  4.73451621e-04 -2.60379054e-02  3.25106300e-01
 -3.80780281e-05 -2.72725003e+00 -2.21220140e-01  9.50794091e-02
  6.40351613e-02  2.73550971e+00 -3.31801241e-04 -9.54325119e-04
  2.74026646e+00 -5.34164892e-04  9.73498582e-04  3.69225052e-03
  3.54487449e-04 -5.43344598e-04 -3.30448035e-01 -1.40800498e-03
  8.31432887e-04  1.02117272e-03 -1.68047416e-03 -5.83664817e-03
 -1.11087997e-02  2.72770997e+00]
loss:0.33968680947709307


In [69]:
#RR
lambda_=0.1
w,loss = ridge_regression(y,tX,lambda_)
print(f'w:{w}\nloss:{loss}')

w:[ 8.03357874e-05 -7.20229357e-03 -6.05414322e-03 -5.47524708e-04
 -1.93892567e-02  4.73474160e-04 -2.60360866e-02  3.25109901e-01
 -3.81780647e-05 -4.25488847e-01 -2.21215574e-01  9.50773063e-02
  6.40334364e-02  4.33748519e-01 -3.32367323e-04 -9.54270952e-04
  4.38505213e-01 -5.32787121e-04  9.72271361e-04  3.69233071e-03
  3.55493260e-04 -5.43272790e-04 -3.30447361e-01 -1.40802204e-03
  8.31788674e-04  1.02083858e-03 -1.68036824e-03 -5.83753485e-03
 -1.11063383e-02  4.25948612e-01]
loss:0.3396876032273416


In [70]:
#LR
initial_w=np.zeros(tX.shape[1])
max_iters=300
gamma=1e-9
w,loss = logistic_regression(y,tX,initial_w,max_iters,gamma)
print(f'w:{w}\nloss:{loss}')

w:[ 6.52327568e+00 -2.51719116e+00 -3.04656915e+00 -1.95857136e+00
  2.13455271e+01  1.61360538e+01  2.13909532e+01 -8.43372250e-02
 -8.14310085e-01 -6.36342267e+00 -6.56042370e-02  1.70165825e-02
  2.13766411e+01 -1.15067443e+00  2.11707940e-04 -2.08867554e-04
 -1.84395107e+00  6.35723274e-04 -9.80819194e-04 -1.68288632e+00
  1.14431941e-03 -8.24124750e+00 -4.50590350e-02  1.27086850e+01
  1.47138710e+01  1.47140174e+01  2.03951076e+01  2.13832539e+01
  2.13827966e+01 -3.36879710e+00]
loss:nan


In [71]:
#RLR
initial_w=np.zeros(tX.shape[1])
max_iters=300
gamma=1e-9
lambda_=0.01
w,loss = reg_logistic_regression(y,tX, lambda_, initial_w, max_iters,gamma)
print(f'w:{w}\nloss:{loss}')

w:[ 6.52327566e+00 -2.51719115e+00 -3.04656914e+00 -1.95857136e+00
  2.13455270e+01  1.61360537e+01  2.13909531e+01 -8.43372248e-02
 -8.14310083e-01 -6.36342265e+00 -6.56042368e-02  1.70165824e-02
  2.13766410e+01 -1.15067443e+00  2.11707939e-04 -2.08867554e-04
 -1.84395107e+00  6.35723272e-04 -9.80819191e-04 -1.68288632e+00
  1.14431941e-03 -8.24124748e+00 -4.50590349e-02  1.27086849e+01
  1.47138710e+01  1.47140174e+01  2.03951075e+01  2.13832539e+01
  2.13827965e+01 -3.36879709e+00]
loss:nan


### Cleaning dataset

#### Transform [-1,1] into [0,1]

In [72]:
#tX[:,:][tX[:,:] == -999] = 0
#we could normalize the data ranging from [0,1] since its binary prediction",
y = (y-min(y))/(max(y)-min(y))


### Remove columns containing over 50% of NULL values

In [73]:
"""remove_features=[]
for i in range(tX.shape[1]):
    col=tX[:,i]
    total=col.shape[0]
    counter_=collections.Counter(col)
    nulls=counter_[-999]
    null_percentage=round(nulls/total,2)
    print(f'NULL percentage is: {null_percentage}')
    if null_percentage>0.5:
        remove_features.append(i)
tX=np.delete(tX,remove_features,1)"""

"remove_features=[]\nfor i in range(tX.shape[1]):\n    col=tX[:,i]\n    total=col.shape[0]\n    counter_=collections.Counter(col)\n    nulls=counter_[-999]\n    null_percentage=round(nulls/total,2)\n    print(f'NULL percentage is: {null_percentage}')\n    if null_percentage>0.5:\n        remove_features.append(i)\ntX=np.delete(tX,remove_features,1)"

In [74]:
"""remove_features=[]
for i in range(tX.shape[1]):
    col=tX[:,i]
    total=col.shape[0]
    counter_=collections.Counter(col)
    nulls=counter_[-999]
    null_percentage=round(nulls/total,2)
    print(f'NULL percentage is: {null_percentage}')
    if null_percentage>0.5:
        remove_features.append(i)
tX=np.delete(tX,remove_features,1)"""

"remove_features=[]\nfor i in range(tX.shape[1]):\n    col=tX[:,i]\n    total=col.shape[0]\n    counter_=collections.Counter(col)\n    nulls=counter_[-999]\n    null_percentage=round(nulls/total,2)\n    print(f'NULL percentage is: {null_percentage}')\n    if null_percentage>0.5:\n        remove_features.append(i)\ntX=np.delete(tX,remove_features,1)"

### Split train set into three sets according to category of jet_num (lot of column depend on this column so splitting will ensure better accuracy!!=

In [75]:
tX_0 = tX[:,:][(tX[:,22] == 0)]
print(tX_0.shape)
tX_1 = tX[:,:][(tX[:,22] == 1)]
print(tX_1.shape)
tX_2 = tX[:,:][(tX[:,22] >= 2)]
print(tX_3.shape)
splitted_dataset = [tX_0,tX_1,tX_2,tX_3]

(99913, 30)
(77544, 30)
(22164, 30)


### Removing outliers (for all 4 datasets)

In [76]:
q1 = []
q2 = []
k = 1
for dataset in splitted_dataset:
    for i in range(0,dataset.shape[1]):
        q1 = np.percentile(dataset[:,i],25)
        mean = np.mean(dataset[:,i])
        q3 = np.percentile(dataset[:,i],75)
        dataset[:,i][(dataset[:,i] < q1 - k*(q3-q1))] = mean
        dataset[:,i][(dataset[:,i] > q3 + k*(q3-q1))] = mean

### Normalization of features


In [77]:
#tX,_,_ = standardize(tX)
    
###for all datasets
for dataset in splitted_dataset:
    dataset,_,_ = standardize(dataset)

[[ 160.937        68.768       103.235      ... -999.
  -999.           46.226     ]
 [  12.84574404   46.05359999   82.21903267 ... -999.
  -999.           44.251     ]
 [ 154.916        10.418        94.714      ... -999.
  -999.           30.638     ]
 ...
 [  12.84574404   78.256        79.699      ... -999.
  -999.           78.984     ]
 [ 133.457        77.54         88.989      ... -999.
  -999.           70.969     ]
 [ 105.457        60.526        75.839      ... -999.
  -999.           41.992     ]]
[4.94019801e+02 2.87160884e+01 1.96201988e+01 1.18620575e+01
 0.00000000e+00 0.00000000e+00 0.00000000e+00 4.39011056e-01
 1.18620576e+01 1.39903827e+01 4.73140841e-01 1.98615037e-01
 0.00000000e+00 8.87296053e+00 1.23342423e+00 1.81734217e+00
 9.74265867e+00 1.31084863e+00 1.81783473e+00 1.48525355e+01
 1.81099743e+00 4.29839994e+01 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00]
[45.75243948 30.44778004 

### Remove less influent features

In [15]:
arr=np.array([5,4,28,1,3])
arr.argsort()[:3]
arr[arr<=3]

[ 5  4 28  1  3]
[ 5  4 28  1  3]
[ 5  4 28  1  3]


In [59]:
#Apply least squares
threshold=1e-3
w,loss = least_squares(y,tX)
print(f'w:{w}\nloss:{loss}')
print(f'w:{w}\n\tshape:{w.shape}')
w=w[np.abs(w)>=threshold]
print(f'w:{w}\n\tshape:{w.shape}')


w:[ 1.16975242e-01 -1.38150093e-01  3.99292663e-02 -1.40284132e-02
 -3.11943953e-02 -1.95051690e-02  2.73461699e-03 -3.06395624e-02
  5.08073509e-02  3.30298815e-02 -1.09746816e-03 -7.30123610e-04
 -6.91177499e-03 -4.81678407e-04  1.61056629e-03 -7.18376228e-03
  1.36619527e-04  8.37007020e-03 -3.31878295e-02  6.62202272e-02
 -4.58988756e-02 -2.22432239e-02  3.71830081e-02]
loss:0.13944857218343729
w:[ 1.16975242e-01 -1.38150093e-01  3.99292663e-02 -1.40284132e-02
 -3.11943953e-02 -1.95051690e-02  2.73461699e-03 -3.06395624e-02
  5.08073509e-02  3.30298815e-02 -1.09746816e-03 -7.30123610e-04
 -6.91177499e-03 -4.81678407e-04  1.61056629e-03 -7.18376228e-03
  1.36619527e-04  8.37007020e-03 -3.31878295e-02  6.62202272e-02
 -4.58988756e-02 -2.22432239e-02  3.71830081e-02]
	shape:(23,)
w:[ 0.11697524 -0.13815009  0.03992927 -0.01402841 -0.0311944  -0.01950517
  0.00273462 -0.03063956  0.05080735  0.03302988 -0.00109747 -0.00691177
  0.00161057 -0.00718376  0.00837007 -0.03318783  0.06622023

### Logistic Cross Validation - Searching best Degree

In [15]:
degrees=np.arange(6)
k_fold=5
max_iters=50
gamma=1e-8
rmse_tr_list=[]
rmse_te_list=[]
for D in degrees:
    #compute loss with cross-validation
    rmse_tr, rmse_te=apply_cross_validation_logistic(y,tX,k_fold,D,max_iters,gamma,1)
    rmse_tr_list.append(rmse_tr)
    rmse_te_list.append(rmse_te)
print(rmse_te_list)
D_best_index=degrees[np.argmin(np.array(rmse_te_list))]
D_best=degrees[D_best_index]
    

[0.5946081976956543, 0.57258475274175, 0.769664518409219, 0.7800454783380737, 1.1340303010250576, 1.3728935014020909]


In [16]:
D_best

1

### Cross Validation Ridge Regression - Best Degree

In [60]:
degrees=np.arange(6)
lambdas=np.logspace(-6,0,10)
k_fold=10
rmse_tr_list=np.zeros((len(degrees),len(lambdas)))
rmse_te_list=np.zeros((len(degrees),len(lambdas)))
for i,D in enumerate(degrees):
    for j,lambda_ in enumerate(lambdas):
        #compute loss with cross-validation
        rmse_tr, rmse_te=apply_cross_validation(y,tX,k_fold,D,lambda_,1)
        rmse_tr_list[i,j]=rmse_tr
        rmse_te_list[i,j]=rmse_te
D_best_index,lambda_best_index=np.unravel_index(np.argmin(rmse_te_list),rmse_te_list.shape)
D_best=degrees[D_best_index]
lambda_best=lambdas[lambda_best_index]
print(f'degree:{D_best} lambda_:{lambda_best}')    

degree:5 lambda_:0.0001


### Testing ridge-regression with best Degree

In [61]:
phi_tX=build_poly(tX,D_best)
w,loss=ridge_regression(y,phi_tX,lambda_best)
print(f'w:{w}\nloss:{loss}')

w:[ 4.49194916e+02  3.37350622e-01 -2.07981427e-01  1.19106993e-02
 -3.21258465e-02 -1.43233988e-02 -2.15183691e-02 -8.27066892e-03
 -3.01615397e-02 -3.91084251e-02  2.85889649e-02 -9.89020450e-04
 -4.05536127e-03 -1.32385199e-02 -1.71464011e-04  2.31157332e-03
 -3.92496271e-03 -6.93262789e-04  8.76510651e-03 -2.39755687e+01
  3.67831678e+01 -4.53846408e+02  1.16963732e+02  2.73576681e-02
 -1.77049329e-02 -5.97305031e-02 -3.17167466e-03  1.51709603e-02
  4.83252214e-03  1.26459450e-04  3.79595880e-02  2.57357457e-02
  3.68755081e-02 -1.01021570e-02 -7.46933219e-03 -9.18574504e-03
 -5.55925907e-03 -3.22946753e-02 -8.23481796e-03 -1.21166419e-02
  1.58333965e-03 -1.02037443e-02  2.80809352e+01 -5.51456944e+01
 -5.02800694e+02  6.65514231e+01 -8.31335366e-02 -8.85960820e-02
  6.07393701e-02  1.04700462e-02 -1.00029537e-03 -1.47836607e-02
  1.38422719e-02 -1.40721501e-02 -5.85230900e-03  1.66241742e-01
 -1.63676379e-03 -4.15861075e-04  4.42018326e-03  9.00625497e-03
  2.23280789e-03  2.808

## Generate predictions and save ouput in csv format for submission:

In [62]:
DATA_TEST_PATH = '../data/test.csv'
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)
tX_test=np.delete(tX_test,remove_features,1)
tX_test,_,_ = standardize(tX_test)
tX_test=build_poly(tX_test,D_best)

[406.01834519  35.39343386  40.47399952  63.30439439   0.77997775
  21.76043127 116.25814329   0.84526994   1.19452041  22.43646206
   1.2132615    1.81577961  22.17629532   1.26392824   1.81442676
  32.31916029   1.81291407 126.95594878   0.97939339 533.15593608
 489.46814712 489.45777374  98.47043502]


In [64]:
weights=w
OUTPUT_PATH = 'output6.csv' # TODO: fill in desired name of output file for submission
y_pred = predict_labels(weights, tX_test)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)